source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MagnetJourney' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Pods for MagnetJourney
  pod 'GoogleMaps'

  target 'MagnetJourneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
